### ISSUE TITLE
[REQUEST] Bigger font for source panels (console, server browser)

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/TF2HUD-Fixes#286]
Fonts for some panels such as dev console or server browser are incredibly small which makes the text very hard to read, even on 1080p. I think increasing the font size would be a nice quality-of-life change considering how often those panels are used?

No kidding, most of the time I have to squint my eyes to read something in both of those panels.

![Screenshot 2024-09-04 215551](https://github.com/user-attachments/assets/eff80df9-435a-4eb5-b469-b83e8b8433d0)

![Screenshot 2024-09-04 215609](https://github.com/user-attachments/assets/a83ffb8a-2a83-4668-a44b-91e5c07b0250)

I set tall value for ConsoleText to 12 (from 10) as a test and it looks a lot better.

![Screenshot 2024-09-04 231927](https://github.com/user-attachments/assets/4d7cb1f1-14f2-4037-aad7-889a89792a17)

**Comment by CriticalFlaw** [comment]
Can you submit this change as a pull request please?

**Comment by CriticalFlaw** [comment]
Added in #287 by @Kruphixx 

![367487160-b9c53f66-9171-42d0-9afc-62e6a10a45c9](https://github.com/user-attachments/assets/b806ff93-079c-43c6-a067-2f45c62c0f0f)

**Comment by valeriedesumo** [comment]
I request for this change to be undone. Not only is it a big difference from the original HUD, it causes problems.

The font change in the console results in significantly less information being visible, from 53 lines down to 42, and with word-wrapping now causing many lines to expand onto two lines. There is also a large space at the bottom that I assume is from there not being enough room for another full line, where those lines are now taller than before.
New:
![image](https://github.com/user-attachments/assets/77ad8edb-8de7-4968-8dc5-7fee29624837)
Original:
![image](https://github.com/user-attachments/assets/583a47db-0263-4b59-9d83-cb8d85753064)

In addition, the "G" from "LOADING" is now cutoff
New:
![image](https://github.com/user-attachments/assets/c224b7fd-854e-4093-8dde-459e461cb0e2)
Original:
![image](https://github.com/user-attachments/assets/8a09d67d-f01c-49a4-91b4-7ef5c9762e9d)

**Comment by valeriedesumo** [comment]
You would say that the departure from the original HUD's look is worth the change? I use this HUD because of how much it sticks to the original, but you can change or just tweak it if you feel that way

**Comment by Kruphixx** [comment]
> You would say that the departure from the original HUD's look is worth the change? I use this HUD because of how much it sticks to the original, but you can change or just tweak it if you feel that way

I really don't see the issue, it's just a font size change...? It still looks like TF2. It's up to @CriticalFlaw, if he want to revert the change altogether then fine.

**Comment by CriticalFlaw** [comment]
I agree that increasing the font size does not deviate from the original in a significant way. In my experience, while editing on an ultrawide monitor it can get hard to read the console and source window text because it does not scale properly. 

@Kruphixx please correct the issues valeriedsumo had brought up brought up.

For anyone who does not like/want this change, you can delete the `resource/sourceschemebase.res` file from your copy of the HUD.

**Comment by CriticalFlaw** [comment]
Updated in https://github.com/CriticalFlaw/TF2HUD-Fixes/pull/309 by @Kruphixx 

![397980413-68244844-25f4-4f60-a7b3-9303827e7845](https://github.com/user-attachments/assets/ebfc42e4-2bac-4a1e-a9dd-d6fc5774f120)
![397980432-5baf8d82-ac95-470b-bba1-8c2822a51c79](https://github.com/user-attachments/assets/92abdb45-50d7-48a2-861e-d5a875636e8b)
