### ISSUE TITLE
[BUG] Killstreak icon and number too close/overlapping when spectating teammates.

### ISSUE THREAD

**Issue by Sizzler48** [CriticalFlaw/TF2HUD-Fixes#288]
**When spectating teammates who have killstreak weapons equipped, the space between the killstreak icon and the current count is too small, making it difficult to read the count.**

* Windows 10
* 1980x1080
* N/A
* N/A
* Spectate teammate with killstreak weapon.

**Screenshots**
![image](https://github.com/user-attachments/assets/af4cb413-f365-4b79-9b5c-0748b22a8d6e)

**Comment by Kruphixx** [comment]
I was able to fix this by adding an anchor then pinning the ks icon to it but it doesn't look that great, had to make some space between the ks icon and number because otherwise they would overlap on 4:3 resolutions. @CriticalFlaw 

![20240913121915_1](https://github.com/user-attachments/assets/70ed69a8-a30d-4a64-91ba-d39a95c12fbb)

![20240913121923_1](https://github.com/user-attachments/assets/f492a15d-0b6b-419b-b886-13cfd4d2c29a)

**Comment by CriticalFlaw** [comment]
> I was able to fix this by adding an anchor then pinning the ks icon to it but it doesn't look that great, had to make some space between the ks icon and number because otherwise they would overlap on 4:3 resolutions. @CriticalFlaw
> 
> ![20240913121915_1](https://private-user-images.githubusercontent.com/50501742/367253227-70ed69a8-a30d-4a64-91ba-d39a95c12fbb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDg4MzcsIm5iZiI6MTcyNjI0ODUzNywicGF0aCI6Ii81MDUwMTc0Mi8zNjcyNTMyMjctNzBlZDY5YTgtYTMwZC00YTY0LTkxYmEtZDM5YTk1YzEyZmJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE3Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2M2EwNzdjNjFhMmFmZjk2YjYzMTY1MWVkOGRkMTlhNGZhYTBhZmEzMzkzNDZlMDFmMmZmZTVlYTFlNmZkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIgsq5E4xRxWnpatyEzLWzqr5JrY5B50iroP_1RoSJs)
> 
> ![20240913121923_1](https://private-user-images.githubusercontent.com/50501742/367253251-f492a15d-0b6b-419b-b886-13cfd4d2c29a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDg4MzcsIm5iZiI6MTcyNjI0ODUzNywicGF0aCI6Ii81MDUwMTc0Mi8zNjcyNTMyNTEtZjQ5MmExNWQtMGI2Yi00MTliLWI4ODYtMTNjZmQ0ZDJjMjlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE3Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTU3MTc2NTAyYmRjZTc4MTFkOWUyMzI3NjgwMmYzM2ZkNDg2ZTU2NzMyNzNjNDc5MGY3ZjI2YmMzNmI4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XuYUWhXRRlEyu4ijohKj_uOANnlSsaAhND1nWVelcuM)

Looks good. Thanks! I recall this being a common fix in custom HUDs and though I'd like to avoid adding extra elements (rather valve fix this properly) this one should be okay. Can you create a PR for this please?

**Comment by CriticalFlaw** [comment]
Completed in #289 by @Kruphixx 
Thanks!

**Comment by Kruphixx** [comment]
Okay I'm not sure if it was already like that but seems the killstreak icon in the normal targetID is a bit mispositioned. Don't see a way of fixing this issue for both normal and spectator targetIDs.

![20240914003208_1](https://github.com/user-attachments/assets/b4c4e90c-0dad-45f9-9958-bcefeaaa2c88)

**Comment by Sizzler48** [comment]
Unsure if this was reported additionally, but the issue occurs on Linux too.

**Comment by Sizzler48** [comment]
> Okay I'm not sure if it was already like that but seems the killstreak icon in the normal targetID is a bit mispositioned. Don't see a way of fixing this issue for both normal and spectator targetIDs.
> 
> ![20240914003208_1](https://private-user-images.githubusercontent.com/50501742/367464218-b4c4e90c-0dad-45f9-9958-bcefeaaa2c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NTg5MDIsIm5iZiI6MTczMDY1ODYwMiwicGF0aCI6Ii81MDUwMTc0Mi8zNjc0NjQyMTgtYjRjNGU5MGMtMGRhZC00NWY5LTk5NTgtYmNlZmVhYWEyYzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNzNiNzE1YzIwMjIzOGE3N2VkYTAyZDc0ZjkzM2EyNDIzYmU3YjY5YzgwM2UxYzVhYmQyYjNiNDZmZTBmNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2VmgpXTQxeiRuZuV6z3naXYMfp9h2VoP-sYGLmUdD5A)

This just a Valve issue?
