### ISSUE TITLE
[BUG] HUD crosshair not displaying on Linux

### ISSUE THREAD

**Issue by Sizzler48** [CriticalFlaw/TF2HUD-Fixes#290]
**Describe the issue.**
The HUD crosshair does not appear on screen during gameplay, despite enabling it and applying a colour in the main menu customisations area.

* Linux Mint 22
* 1980x1080
* N/A
* Stock TF2 install
* Install HUD on Linux, enable HUD Crosshair feature in Customisations, load into match

**Screenshots**
N/A

**Comment by CriticalFlaw** [comment]
After you click "Enable" on the Customization screen, did you also click on the green "Apply" button? On Windows it looks to work as expected

**Comment by Sizzler48** [comment]
Yes I pressed the colour and hit apply. Restarted game too. Just shows default white colour crosshair.
________________________________

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of it? A white circle is the default, color changes take effect after a game restart. Does applying a different crosshair style work?

**Comment by Sizzler48** [comment]
![image](https://github.com/user-attachments/assets/d4a04fe6-c6cc-4c80-a79c-5c6fb55506c8)

Different crosshair styles don't work. I have "crosshair 0" in my config for TF2's builtin Valve default crosshair since I exclusively use HUD crosshairs provided by HUD developers.

**Comment by Sizzler48** [comment]
Apologies: me saying that the default white crosshair appears is false: no crosshair appears at all, even after applying different styles and doing a game restart.

This HUD crosshair had no issues a few weeks ago when I was on Windows.

**Comment by CriticalFlaw** [comment]
Got it. Thank you. Do you have the `Team Fortress 2/tf/cfg/hud_crosshair_visibility.txt` file?

If not, you could try going to the hud-fixes folder then open `resource/ui/#customizations/crosshair/crosshair_base.res` and change "visible" to 1 like so
![image](https://github.com/user-attachments/assets/ba653991-9b83-4546-b4b3-6fa17da87592)

**Comment by Sizzler48** [comment]
[hud_crosshair_visibility.txt](https://github.com/user-attachments/files/17002936/hud_crosshair_visibility.txt)

Text file has crosshair set to 1.

I'll try your second method now and see if that works.

**Comment by Sizzler48** [comment]
![image](https://github.com/user-attachments/assets/1cc1a27c-c373-4ff7-a9fa-f9fe211087b3)

Crosshair is here thank you! I had to do your resource/ui method. Visible was set to 0 in there for some reason.

**Comment by Sizzler48** [comment]
How would I go about changing the crosshair colour and adding "flash on hit?"

**Comment by CriticalFlaw** [comment]
The flash on hit should be on by default.

The color can be changed by changing the value of fgColor from Crosshair to an RGBA value

**Comment by Sizzler48** [comment]
Flash on hit is working fine. I'll change colour and report back.

**Comment by Sizzler48** [comment]
![image](https://github.com/user-attachments/assets/f472c3bb-3aba-41ac-9a56-d1ac71c71058)

Everything is working great now! Thank you CriticalFlaw!

Is the killstreak icon fix for spectators going to be pushed to next release of CHF?

**Comment by Sizzler48** [comment]
One last issue: it reverts back to white (the crosshair colour) upon doing damage to an enemy.

**Comment by CriticalFlaw** [comment]
> One last issue: it reverts back to white (the crosshair colour) upon doing damage to an enemy.

Oh right, my bad. The place where you can change the crosshair color (and hitmarker) is actually in `resource/ui/#customizations/crosshair/crosshair_scheme.res` see below:

![image](https://github.com/user-attachments/assets/c8ed740e-4cc8-49fa-a4d5-d0d778845855)

> Is the killstreak icon fix for spectators going to be pushed to next release of CHF?

Yes

**Comment by Sizzler48** [comment]
Thank you for the updated info. You've been a major big help! :)

Last one I promise lol: may we have an estimated time frame for the next release? I wonder if people have been requesting quickplay from mastercomfigs.

**Comment by qkeitoe** [comment]
@CriticalFlaw regarding this issue, check out https://github.com/Hypnootize/m0rehud/pull/41, https://github.com/Hypnootize/m0rehud/issues/40#issuecomment-1779949335 and https://github.com/Hypnootize/m0rehud/issues/53#issuecomment-2060800566

**Comment by CriticalFlaw** [comment]
> @CriticalFlaw regarding this issue, check out [Hypnootize/m0rehud#41](https://github.com/Hypnootize/m0rehud/pull/41), [Hypnootize/m0rehud#40 (comment)](https://github.com/Hypnootize/m0rehud/issues/40#issuecomment-1779949335) and [Hypnootize/m0rehud#53 (comment)](https://github.com/Hypnootize/m0rehud/issues/53#issuecomment-2060800566)

The #base in this mod already go 4-levels down (see: https://github.com/CriticalFlaw/TF2HUD-Fixes/blob/main/resource/ui/%23customizations/crosshair/crosshair_color.res)

So wouldn't changing it to 6-levels break on Windows? Worth a try but I'm not too sure.

**Comment by qkeitoe** [comment]
Basically, you should go down 2 more levels down on Linux than you normally do on Windows in all `#base` statements referring to files outside of a HUD folder (for example, in the `tf/cfg` folder). These extra levels are the HUD folder and the `custom` folder.

But, if nothing has changed since then, according to my tests at that time https://github.com/Hypnootize/m0rehud/pull/41#issuecomment-1778986851, it's not a problem since both variants (for some reason) work on Windows.

The main problem on Linux is the need to use a HUD folder name in #base statements in generated files., like this:
https://github.com/Hypnootize/m0rehud/blob/02629de0ab62ae8611d9979b5bbf331bb123ca90/cfg/m0re_customization_general.cfg#L8

**Comment by CriticalFlaw** [comment]
Apologies for the long delay. This should now be fixed in a001121b3939414b5b8fe135098cb54912068f1f. From my testing it still works on Windows so hopefully it will work on Linux now too. Please retest to validate. Cheers

**Comment by CriticalFlaw** [comment]
Closing as done.
