### ISSUE TITLE
[REQUEST] need some help editing in hud

### ISSUE THREAD

**Issue by Saint-Son** [CriticalFlaw/TF2HUD-Fixes#292]
hello, I would like to change 2 things in hud

first is to remove the hitmarker from the crosshairs
second is to increase the health value in TargetID

**Comment by CriticalFlaw** [comment]
To remove the hitmarker, comment out or remove this code block: https://github.com/CriticalFlaw/TF2HUD-Fixes/blob/main/scripts/hudanimations_custom.txt#L15-L25

To increase the size of the health value on the TargetID, you'll first need to download this file: https://github.com/Hypnootize/TF2-Default-HUD/blob/master/resource/ui/spectatorguihealth.res and put into the HUD's `resource/ui/` folder.

You can then increase the health value by changing the `font` value under `PlayerStatusHealthValue`: https://github.com/Hypnootize/TF2-Default-HUD/blob/master/resource/ui/spectatorguihealth.res#L91

All available font options can be found here: https://github.com/CriticalFlaw/TF2HUD-Fixes/blob/main/resource/clientscheme.res#L2282

Hope that helps. Good luck

**Comment by Saint-Son** [comment]
I started checking everything and I can’t figure out where all the fonts start and end.
