### ISSUE TITLE
[BUG] When will the UI scaling issues that was introduced by the scream fortress update be patched?

### ISSUE THREAD

**Issue by MrConeMan** [CriticalFlaw/TF2HUD-Fixes#295]
**Describe the issue.**
I tend to use this hud a lot since it makes the default TF2 hud feel more cleaner than the actual default hud. However when the UI scaling update was implemented, it introduced a couple issues I believe should be adressed (Example: Buttons look too big and the scoreboard not displaying casual ranks)

* OS: Windows 11
* Res: 1920x1080

**Screenshots**
N/A

**Comment by CriticalFlaw** [comment]
They've been patched in the main branch and on the Gamebanana release.

Direct download: https://github.com/CriticalFlaw/TF2HUD-Fixes/archive/refs/heads/main.zip

GameBanana: https://gamebanana.com/mods/26450
