### ISSUE TITLE
[BUG] Arena respawn label overlaps VSH healthbar

### ISSUE THREAD

**Issue by Sizzler48** [CriticalFlaw/TF2HUD-Fixes#296]
**UI overlap on Outburst VSH between Saxton's health and "no respawning in Arena Mode" text**
A clear and concise description of the issue. Please include details such as the

* Linux Mint 22
* 1920 x 1080
* N/A
* N/A
* Load into Outburst, die.

**
![image](https://github.com/user-attachments/assets/b855724e-d79f-4b2f-9707-32060ca76db4)
**

**Comment by CriticalFlaw** [comment]
Fixed in 69e2caacd82f843d35737a00d0aff4372b2f3611 for both standard and hell variants.

![20241105230330_1](https://github.com/user-attachments/assets/5f3a019e-f28b-43f6-8907-306c9129b77b)
![20241105230332_1](https://github.com/user-attachments/assets/fe19371c-cfe7-43a4-bd75-acc81edbb56b)
