### ISSUE TITLE
[BUG] Overlap between seeing teammate killstreak count and killstreak icon.

### ISSUE THREAD

**Issue by Sizzler48** [CriticalFlaw/TF2HUD-Fixes#297]
**Describe the issue.**
Similar to the overlap on teammate spectate bug, but when alive and looking at teammates.

* Debian 12
* 1920x1080
* N/A
* N/A
* Load into map, look at teammate who has killstreak weapon and has >1 active streak.

**Comment by CriticalFlaw** [comment]
This has already been fixed in https://github.com/CriticalFlaw/TF2HUD-Fixes/issues/288 by Kruphixx but not yet released.

Please download the latest version from [here](https://github.com/CriticalFlaw/TF2HUD-Fixes/archive/refs/heads/main.zip) or GameBanana.
