### ISSUE TITLE
[BUG] Competitive rank medal appears too small on match summary screen

### ISSUE THREAD

**Issue by MrConeMan** [CriticalFlaw/TF2HUD-Fixes#298]
**Describe the issue.**
Before the ui scaling update it used to be normal size and now its been shrunk down to a pretty small size. I know this is probably a low priority issue since nobody really plays competitive but I thought id put it out here

* Windows 11
* 1920x1080
* Steps to reproduce the issue: Find a match on competitive

![image](https://github.com/user-attachments/assets/7f230046-b784-4aca-98a6-264b89ac680e)

**Comment by CriticalFlaw** [comment]
@Kruphixx apologies for the ping. Is this something you've seen or could help with? You've done good work with the badge on other issues.

**Comment by MrConeMan** [comment]
@CriticalFlaw @Kruphixx I forgot to mention on the main menu if you are at a high casual level the badge sort of cuts off on both sides. I don't have a direct screenshot of it since rn Im at casual level 80 tier 2 but I can provide a small example 
![image](https://github.com/user-attachments/assets/459de0d5-7d92-4fc2-8af4-58e430ecba91)

**Comment by Kruphixx** [comment]
> @Kruphixx apologies for the ping. Is this something you've seen or could help with? You've done good work with the badge on other issues.

Sorry I was gonna respond to this but forgot in the end. 

I know a potential fix but don't really have a way to test it.

**Comment by CriticalFlaw** [comment]
> > @Kruphixx apologies for the ping. Is this something you've seen or could help with? You've done good work with the badge on other issues.
> 
> Sorry I was gonna respond to this but forgot in the end.
> 
> I know a potential fix but don't really have a way to test it. I can still make a PR though.

yes please, can have McConeMan test the PR

**Comment by MrConeMan** [comment]
> > > @Kruphixx apologies for the ping. Is this something you've seen or could help with? You've done good work with the badge on other issues.
> 
> > 
> 
> > Sorry I was gonna respond to this but forgot in the end.
> 
> > 
> 
> > I know a potential fix but don't really have a way to test it. I can still make a PR though.
> 
> 
> 
> yes please, can have McConeMan test the PR

Im on vacation right now but I should be able to test it by next week
