### ISSUE TITLE
[BUG] ...MvM Canteen Hud Element is in the wrong location

### ISSUE THREAD

**Issue by Lego1upMushroom** [CriticalFlaw/TF2HUD-Fixes#299]
![{CF40F576-93A8-49F2-A3DC-D2B096DC7E9D}](https://github.com/user-attachments/assets/0c10690e-4a0c-4e63-a33f-88c7cbc9f9e8)

**Comment by CriticalFlaw** [comment]
This has already been fixed in https://github.com/CriticalFlaw/TF2HUD-Fixes/issues/274 but not yet released.

Please download the latest version from [here](https://github.com/CriticalFlaw/TF2HUD-Fixes/archive/refs/heads/main.zip) or GameBanana.
