### ISSUE TITLE
[BUG] Floating damage font reverts to default over time

### ISSUE THREAD

**Issue by Katzenwerfer** [CriticalFlaw/TF2HUD-Fixes#301]
**Describe the issue.**
I noticed that whenever the "TF2 Secondary" font is selected for the floating damage, it reverts over time back to the default font. I'm unsure if this also happens with the last damage font, but I'll keep an eye on it.

Most of my personal config consists of aliases and bind scripts stuff. Graphics are entirely handled by mastercomfig.

I will try to record it later, since it seems relatively easy to reproduce. Just enter a game, set your font and start doing damage.

**Comment by CriticalFlaw** [comment]
If you could record it, that would be great because fonts don't revert on their own unless there's a conflict with another mod.

**Comment by CriticalFlaw** [comment]
Closing due to lack of information/proof. This should not happen in normal cases.

**Comment by Katzenwerfer** [comment]
Sorry, I never got to dedicate time into trying to record it since I don't know the exact setup to replicate it, so I ultimately opted for hard-coding the fonts on my side.

**Comment by Katzenwerfer** [comment]
Since I've been digging into the files, I noticed that selecting the `TF2 Build` floating damage font sets it for normal damage, but not crit damage. I suppose it is intended, but it explains why I was noticing the normal font "flashing" me at times.
