### ISSUE TITLE
[BUG] targetid.res misalligned/overlapping killstreak counter

### ISSUE THREAD

**Issue by Sizzler48** [CriticalFlaw/TF2HUD-Fixes#306]
**Describe the issue.**
Misalligned current killstreak count overlaps with icon when looking at players when actively playing.

* Linux Mint 22
* 1920x1080
* N/A
* N/A
* Look at player with active killstreak weapon.

**Screenshots**

**Comment by CriticalFlaw** [comment]
Please post a screenshot because if I recall this has already been fixed in https://github.com/CriticalFlaw/TF2HUD-Fixes/commit/fb167b42581e160264e2a8fd1afd2fc7e7897493 by @Kruphixx

**Comment by Sizzler48** [comment]
![image](https://github.com/user-attachments/assets/4c11c306-4411-446a-939f-3402ee71f9bf)

**Comment by Sizzler48** [comment]
> Please post a screenshot because if I recall this has already been fixed in [fb167b4](https://github.com/CriticalFlaw/TF2HUD-Fixes/commit/fb167b42581e160264e2a8fd1afd2fc7e7897493) by @Kruphixx

Seems it was mentioned here by Kruphixx.

https://github.com/CriticalFlaw/TF2HUD-Fixes/issues/288#issuecomment-2350573895

**Comment by CriticalFlaw** [comment]
Fixed in 0e21f42a03d21e02663801df905f7f93e81f8cf9. Please retest and let me know if it worked

**Comment by Sizzler48** [comment]
Retested on Windows 10 (Given up on Linux: too many issues) and works great! Thank you tons for your support!
