### ISSUE TITLE
[BUG] VSH HUD has the alive player count outside the box

### ISSUE THREAD

**Issue by Whurrhurr** [CriticalFlaw/TF2HUD-Fixes#307]
title. fresh install with no other conflicting HUD mods.

**Screenshots**
![image](https://github.com/user-attachments/assets/83e437ba-67ec-4c8d-820f-1223b3d095e0)

**Comment by Whurrhurr** [comment]
should mention it displays fine on maps where the mercs are on the BLU team.
![image](https://github.com/user-attachments/assets/c841ec9b-a036-497c-aa87-fc1bdc94b65c)

**Comment by CriticalFlaw** [comment]
Can you clarify which VSH maps you're seeing the issue?
