### ISSUE TITLE
[REQUEST] need help with customization

### ISSUE THREAD

**Issue by Saint-Son** [CriticalFlaw/tf2hud-fixes#308]
I know you've already answered some of the requests, but I deleted that reply (there was too much spam in the mail)

Anyway:
1. I need to remove the hitmarker from the HUD

2. I also need to remove the table with records for the class. For example: For this life you have the most dominations or For this life you approached the record for kills. 

3. And it would be necessary to find lines to change the font on health indicators in TargetID

**Comment by Saint-Son** [comment]
https://imgur.com/gallery/2T9EPZu
About the second request. Here is a screenshot showing everything. I want to delete this record plate and put the TargetID in its place.

**Comment by CriticalFlaw** [comment]
1. To disable the hitmarker but keep the crosshair, go to the HUD folder and open `scripts/hudanimations_custom.txt` then remove these animation events: https://github.com/CriticalFlaw/TF2HUD-Fixes/blob/main/scripts/hudanimations_custom.txt#L57-L67

2. In the same folder as above, open `hudlayout.res`, find the element **StatPanel** and change its wide value to 0

3. That can be found in `resource/ui/spectatorguihealth.res` under the element **PlayerHealthValue**. The font entry is set to HudFontMediumSmallBold

**Comment by Saint-Son** [comment]
That seems to be all. Thanks

**Comment by CriticalFlaw** [comment]
Great. Have a good one
